- name: heka-configure | Create openstack decoder toml files
  template: src=decoder-openstack.toml.j2 dest={{heka_etc_dir}}/decoder-openstack.toml
  notify: hekad restart

- set_fact:
     splitter_name='openstack'
     splitter_delimiter='\n'
- name: heka-configure | Setup openstack splitter
  template: src=token_splitter.j2 dest={{heka_etc_dir}}/splitter-openstack.toml
  notify: hekad restart

- name: heka-configure | Configure glance logstreamer
  template: src=logstreamer-glance.toml.j2 dest={{heka_etc_dir}}/logstreamer-glance.toml
  notify: hekad restart
